name: txt
description: Simple text editor/notepad with cloud sync.

version: 0.1.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.18.0


dependencies:
  flutter:
    sdk: flutter
  async: ^2.4.1
  background_fetch: ^0.7.2
  dropbox_client: ^0.8.0
  flutter_secure_storage: ^4.1.0
  google_fonts: ^2.0.0
  googleapis: ^2.0.0
  googleapis_auth: ^1.1.0
  html_unescape: ^2.0.0
  json2yaml: ^1.0.1+1
  markdown: ^4.0.0
  mime_type: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  nextcloud: ^3.0.0
  open_file: ^3.0.1
  path: ^1.7.0
  path_provider: ^2.0.1
  pref: ^2.0.2
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  tuple: ^2.0.0
  url_launcher: ^6.0.3
  watcher: ^1.0.0
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4

flutter:
  uses-material-design: true
  fonts:
  - family: Txt
    fonts:
    - asset: assets/icons/Txt.ttf
  assets:
#  - secrets.yaml
  - assets/icon-squircle.png
  - assets/avatars/janheinrichreimer.png
  - assets/avatars/kevinaguilar.png
  - assets/avatars/marvinmeissner.png
