name: txt
description: Simple text editor/notepad with cloud sync.

version: 0.1.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.18.0

dependencies:
  flutter:
    sdk: flutter
  markdown: ^2.1.3
  html_unescape: ^1.0.1+3
  path_provider: ^1.6.11
  google_fonts: ^1.1.0
  preferences: ^5.1.0
  provider: ^4.0.4
  url_launcher: ^5.4.2
  shared_preferences: ^0.5.6+3
  googleapis: ^0.55.0
  googleapis_auth: ^0.2.12
  flutter_secure_storage: ^3.3.3
  yaml: ^2.2.1
  watcher: ^0.9.7+15
  async: ^2.4.1
  background_fetch: ^0.5.1
  tuple: ^1.0.3
  mime_type: ^0.3.2
  open_file: ^3.0.1
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4

flutter:
  uses-material-design: true
  fonts:
  - family: Txt
    fonts:
    - asset: assets/icons/Txt.ttf
  assets:
  - secrets.yaml
  - assets/icon-squircle.png
  - assets/avatars/janheinrichreimer.png
  - assets/avatars/kevinaguilar.png
  - assets/avatars/marvinmeissner.png
