name: txt
description: Simple Text Editor / Notepad with Cloud Sync.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  markdown: ^2.0.3
  flutter_markdown: ^0.2.0
  #    path: ../../../../Open Source/flutter_markdown
  path_provider: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
